name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ldid (Signing Tool)
        run: |
          brew install ldid

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Unzip and Rename Game SDK
        run: |
          unzip SDK.zip
          # الكود أدناه يبحث عن المجلد المستخرج أياً كان اسمه ويغيره إلى SDK تلقائياً ليتوافق مع الـ Makefile
          find . -maxdepth 1 -type d ! -name "." ! -name ".git" ! -name ".github" -exec mv {} SDK \; 2>/dev/null || true

      - name: Build
        run: |
          make clean
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RavFenShadowDylib
          path: .theos/obj/debug/*.dylib
