name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ldid (Signing Tool)
        run: |
          brew install ldid

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Unzip Game SDK
        run: |
          # فك الضغط مع فرض الاستبدال تلقائياً (-o) لتجنب التوقف والأسئلة
          unzip -o SDK.zip || true
          
          # فحص احتياطي: لو تم فك الملفات مباشرة بالخارج بدون مجلد، سنقوم بإنشاء مجلد SDK ونقلها إليه
          if [ ! -d "SDK" ]; then
            mkdir -p SDK
            mv *.hpp SDK/ 2>/dev/null || true
            mv *.h SDK/ 2>/dev/null || true
          fi
      - name: Build
        run: |
          make clean
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RavFenShadowDylib
          path: .theos/obj/debug/*.dylib
